import { Category } from '@prisma/client';

export const Colors = [
  'Black',
  'Blue',
  'Brown',
  'Green',
  'Grey',
  'Multicolor',
  'Metallic',
  'Orange',
  'Purple',
  'Red',
  'White',
  'Yellow',
  'Other'
] as const;
export type Color = typeof Colors[number];
export const Locations = [
  '205 S. Craig (2SC)',
  '300 S. Craig (3SC)',
  '311 S. Craig (CA)',
  '407 S. Craig (4SC)',
  '417 S. Craig (CC)',
  '4516 Henry (UT)',
  '4609 Winthrop (GL)',
  '4615 Forbes (FRB)',
  '4616 Henry (INI)',
  '4620 Henry (PO)',
  '4721 Fifth Ave. (MC)',
  '6555 Penn (PE)',
  'Alumni House (AH)',
  'ANSYS Hall (AN)',
  'Baker Hall (BH)',
  'Bakery Square (BK)',
  'Bramer House (BR)',
  'Cohon University Center (CUC)',
  'Collaborative Innovation Center (CIC)',
  'College of Fine Arts (CFA)',
  'Cyert Hall (CYH)',
  'Doherty Hall (DH)',
  'Facilities Management Building (FM)',
  'FMS Roads & Grounds (FR)',
  'Gates and Hillman Centers (GHC)',
  'Hall of the Arts (HOA)',
  'Hamburg Hall (HBH)',
  'Hamerschlag Hall (HH)',
  'Hunt Library (HL)',
  'Integrated Innovation Institute (III)',
  'Margaret Morrison Carnegie Hall (MM)',
  'Mellon Institute (MI)',
  'Melwood Ave. (MEL)',
  'Mill 19 (M19)',
  'National Robotics Engineering Cent. (NR)',
  'Newell-Simon Hall (NSH)',
  'Osher Lifelong Learning Institute (OSH)',
  'Pittsburgh Technology Center (PTC)',
  'Porter Hall (PH)',
  'Posner Center (PC)',
  'Posner Hall (POS)',
  'PPG 6477 (PP)',
  'Purnell Center for the Arts (PCA)',
  'Rand Building (RA)',
  'Roberts Engineering Hall (REH)',
  'Scaife Hall (4805FREW)',
  'Scott Hall (SC)',
  'Skibo Gymnasium (100TECH)',
  'Smith Hall (EDS)',
  'Software Engineering Institute (SEI)',
  'TCS Hall (TCS)',
  'Tepper Building (TEP)',
  'Warner Hall (WH)',
  'Wean Hall (WEH)',
  'West Wing (WWG)',
  'Whitfield Hall (WF)',
  'WQED Building (WQ)',
  'Other'
];
export type Location = typeof Locations[number];
export const Categories: Record<Category, string> = {
  CLOTHING: 'Clothing',
  UMBRELLA: 'Umbrellas',
  EYEWARE_CASE: 'Glasses/Sunglasses/Cases',
  JEWELRY: 'Jewelry',
  WATCH: 'Watches',
  BEVERAGE_CONTAINER: 'Beverage Containers',
  CHARGER: 'Chargers',
  HEADPHONE_CASE: 'Headphones/Earbuds/Case',
  LAPTOP: 'Laptops',
  PHONE: 'Phones',
  TABLET: 'Tablets',
  OTHER: 'Other'
};
